import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/widgets/header';

import { Provider } from 'react-redux';
import Providers from './store/Providers';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout(props: any) {
	return (
		<html lang='en'>
			<body>
				<Providers>
					<Header />
					{props.children}
					{props.team}
					{props.posts}
				</Providers>
			</body>
		</html>
	);
}
